
stages:
  - build
  - test
  - deploy

build-back:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:latest
  script:
  - echo "Compiling the code..."
  - cd backend
  - mvn validate compile install
  rules:
    - changes:
      - backend/**/*

build-front:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:latest
  script:
  - echo "Compiling the code..."
  - cd FrontEnd
  - npm install --force
  - CI=false npm run build
  rules:
    - changes:
      - frontend/**/*

test:   # This job runs in the test stage.
  stage: test   
  script:
    - echo "Running unit tests..."
  rules:
    - changes:
      - backend/**/*

test-front:   # This job runs in the test stage.
  stage: test   
  script:
    - echo "Running unit tests..."
  rules:
    - changes:
      - frontend/**/*

deploy-back:      # This job runs in the deploy stage.
  stage: deploy
  image: alpine:3.11
  script:
    - echo "Deploying application backend..."
    - echo "Application backend successfully deployed."
    - cd backend/
  rules:
    - changes:
      - backend/**/* 

deploy-front:      # This job runs in the deploy stage.
  stage: deploy
  image: python:latest
  script:
    - echo "Deploying application. FrontEnd.."
    - apt-get update
    - apt-get -y upgrade
  rules:
    - changes:
      - frontend/**/*
    
    


